# Generated by Django 2.1.7 on 2019-03-13 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forcing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(default='')),
                ('display_name', models.TextField(default='')),
                ('description', models.TextField(default='')),
                ('is_active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LoggingMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(default='')),
                ('message', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('forcing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              related_name='loggingmessages', to='noos_services.Forcing')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='')),
                ('country', models.TextField(default='')),
                ('hostname', models.TextField(default='')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='NoosModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(default='')),
                ('display_name', models.TextField(default='')),
                ('description', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='SimulationDemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('json_txt', models.TextField(default='{}')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                           related_name='simulations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField(default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('json_txt', models.TextField(default='{}')),
                ('forcing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                              related_name='uploadedfiles', to='noos_services.Forcing')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploadedfiles',
                                           to='noos_services.Node')),
                ('noos_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                 related_name='uploadedfiles', to='noos_services.NoosModel')),
                ('simulation',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploadedfiles',
                                   to='noos_services.SimulationDemand')),
            ],
        ),
        migrations.AddField(
            model_name='node',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='nodes', to='noos_services.NoosModel'),
        ),
        migrations.AddField(
            model_name='node',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes',
                                    to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='loggingmessage',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loggingmessages',
                                    to='noos_services.Node'),
        ),
        migrations.AddField(
            model_name='loggingmessage',
            name='noos_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='loggingmessages', to='noos_services.NoosModel'),
        ),
        migrations.AddField(
            model_name='loggingmessage',
            name='simulation_demand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loggingmessages',
                                    to='noos_services.SimulationDemand'),
        ),
    ]
