# Generated by Django 2.1.7 on 2019-03-26 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noos_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='forcing',
            name='use_type',
            field=models.TextField(default='O'),
        ),
    ]
