# Generated by Django 2.1.7 on 2019-03-26 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('noos_services', '0002_add_use_type_to_forcings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForcingCouple',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meteorological', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                     related_name='couple_b', to='noos_services.Forcing')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                           related_name='forcing_couples', to='noos_services.Node')),
                ('oceanical', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                                related_name='couple_a', to='noos_services.Forcing')),
            ],
        ),
    ]
