# Generated by Django 2.1.7 on 2019-03-26 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noos_services', '0003_add_forcing_couple_concept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forcingcouple',
            name='node',
        ),
        migrations.AddField(
            model_name='forcingcouple',
            name='noos_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forcing_couples', to='noos_services.NoosModel'),
        ),
    ]
