# Generated by Django 2.1.7 on 2019-03-27 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('noos_services', '0004_link_forcing_couple_to_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loggingmessage',
            name='forcing',
        ),
        migrations.AddField(
            model_name='loggingmessage',
            name='forcing_couple',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='loggingmessages', to='noos_services.ForcingCouple'),
        ),
    ]
