# Generated by Django 2.1.8 on 2019-04-30 09:16

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('noos_services', '0007_forcing_couple_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationdemand',
            name='json_txt',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='json_txt',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
