# Generated by Django 2.2.1 on 2019-05-21 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noos_services', '0008_changing_json_txt_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationdemand',
            name='protected',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='simulationdemand',
            name='status',
            field=models.TextField(default='', null=True),
        ),
    ]
