# Generated by Django 2.2.3 on 2019-07-15 11:07

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('noos_services', '0011_auto_20190618_0802'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mma_result', jsonfield.fields.JSONField(default=dict)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_result', to='noos_services.SimulationDemand')),
            ],
        ),
    ]
