# Generated by Django 2.2.3 on 2019-08-12 07:01

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('noos_services', '0012_analysisresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('idx', models.IntegerField()),
                ('element_type', models.TextField(default='')),
                ('json_data', jsonfield.fields.JSONField(default=dict)),
                ('forcing_couple', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulation_elements', to='noos_services.ForcingCouple')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_elements', to='noos_services.Node')),
            ],
        ),
        migrations.AddField(
            model_name='forcing',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='noosmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='AnalysisResult',
        ),
        migrations.AddField(
            model_name='simulationelement',
            name='noos_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='simulation_elements', to='noos_services.NoosModel'),
        ),
        migrations.AddField(
            model_name='simulationelement',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_elements', to='noos_services.SimulationDemand'),
        ),
    ]
