# Generated by Django 2.2.3 on 2019-08-14 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('noos_services', '0014_change_some_model_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationelement',
            name='next_element',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='noos_services.SimulationElement'),
        ),
        migrations.AddField(
            model_name='simulationelement',
            name='previous_element',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='noos_services.SimulationElement'),
        ),
    ]
