# Generated by Django 2.2.5 on 2019-09-30 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noos_services', '0016_auto_20190822_1326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulationelement',
            name='next_element',
        ),
        migrations.RemoveField(
            model_name='simulationelement',
            name='previous_element',
        ),
    ]
