# Generated by Django 2.2.5 on 2019-10-04 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noos_services', '0018_auto_20191004_0807'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulationcloud',
            old_name='forcing_coupple',
            new_name='forcing_couple',
        ),
    ]
