# Generated by Django 2.2.6 on 2019-12-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noos_services', '0021_auto_20191216_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationdemand',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
