# Generated by Django 2.2.6 on 2020-01-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noos_services', '0022_simulationdemand_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulationdemand',
            name='status',
            field=models.TextField(default='SUBMITTED'),
        ),
    ]
