# Generated by Django 2.1.8 on 2019-05-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noos_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
