"""
Django settings for noosDrift project.

Generated by 'django-admin startproject' using Django 2.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""
import datetime
import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

CENTRAL_ROLE = "Central"
NODE_ROLE = "Node"

NOOS_NODE_ID = "NOOS_NODE_ID"
NOOS_USERNAME = "NOOS_USERNAME"
NOOS_USERPWD = "NOOS_USERPWD"
NOOS_ROLE = "NOOS_ROLE"
NOOS_CENTRAL = "NOOS_CENTRAL"
# NOOS_SFTP_USER = ""
# NOOS_SFTP_HOST = ""
# NOOS_SFTP_PWD = ""
# NOOS_SFTP_KEYFILE = None

ENV_VARS = (NOOS_NODE_ID, NOOS_USERNAME, NOOS_USERPWD, NOOS_ROLE, NOOS_CENTRAL)

ENV_DICT = {}

# USUAL variables, needed on Node and Central
for env_var_name in ENV_VARS:
    env_value = os.environ.get(env_var_name)
    if env_value is None:
        print("No {} defined and exported in bash environment".format(env_var_name))
        assert env_value is not None, "No {} defined and exported in bash environment".format(env_var_name)

    ENV_DICT[env_var_name] = env_value

NOOS_USER = {"username": ENV_DICT[NOOS_USERNAME], "pwd": ENV_DICT[NOOS_USERPWD]}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# URL the API schema should give
SCHEMA_URL = 'http://nameofcentralmachine:8000/'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("NOOS_SECRET_KEY")
if SECRET_KEY is None:
    print("No NOOS_SECRET_KEY defined and exported in bash environment")
    assert SECRET_KEY is not None, "No NOOS_SECRET_KEY defined and exported in bash environment"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['127.0.0.1', 'yourmachinename']

# Application definition

INSTALLED_APPS = [
    'whitenoise.runserver_nostatic',
    'noos_services.apps.NoosServicesConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'noosDrift.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media'
            ],
        },
    },
]

WSGI_APPLICATION = 'noosDrift.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

TEMPLATE_DIRS = (os.path.join(BASE_DIR, 'templates'),)
TEMPLATE_URL = '/noosdrift/api/templates/'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

# in order to copy statics of different plugins to  /static/ directory
# python manage.py collectstatic

STATIC_DIR = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [STATIC_DIR, ]
STATIC_URL = '/noosdrift/api/static/'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

MEDIA_DIR = os.path.join(BASE_DIR, 'media')
MEDIA_ROOT = MEDIA_DIR
MEDIA_URL = '/noosdrift/api/media/'

REQUESTS_DIR = os.path.join(BASE_DIR, 'requests')

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_jwt.authentication.JSONWebTokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    # https://www.django-rest-framework.org/api-guide/throttling/
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle'
    ),
    'DEFAULT_THROTTLE_RATES': {
        'anon': '200/day',  # 50   for each node + central
        'user': '1000/day'  # 1000 request a day allowed by authenticated user
    }
}

# Configure the JWTs to expire after 1 hour, and allow users to refresh near-expiration tokens
JWT_AUTH = {
    'JWT_ENCODE_HANDLER': 'rest_framework_jwt.utils.jwt_encode_handler',
    'JWT_DECODE_HANDLER': 'rest_framework_jwt.utils.jwt_decode_handler',
    'JWT_PAYLOAD_HANDLER': 'rest_framework_jwt.utils.jwt_payload_handler',
    'JWT_PAYLOAD_GET_USER_ID_HANDLER': 'rest_framework_jwt.utils.jwt_get_user_id_from_payload_handler',
    'JWT_RESPONSE_PAYLOAD_HANDLER': 'rest_framework_jwt.utils.jwt_response_payload_handler',
    'JWT_SECRET_KEY': SECRET_KEY,
    'JWT_GET_USER_SECRET_KEY': None,
    'JWT_PUBLIC_KEY': None,
    'JWT_PRIVATE_KEY': None,
    'JWT_ALGORITHM': 'HS256',
    'JWT_VERIFY': True,
    'JWT_VERIFY_EXPIRATION': True,
    'JWT_LEEWAY': 0,
    'JWT_EXPIRATION_DELTA': datetime.timedelta(hours=1),
    'JWT_AUDIENCE': None,
    'JWT_ISSUER': None,
    'JWT_ALLOW_REFRESH': True,
    'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(hours=1),
    'JWT_AUTH_HEADER_PREFIX': 'JWT',
    'JWT_AUTH_COOKIE': None,
}

# Enables django-rest-auth to use JWT tokens instead of regular tokens.
REST_USE_JWT = True

LOGS_DIR = os.path.join(BASE_DIR, 'logs')
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            # 'format': '%(levelname)s %(asctime)s %(module)s %(process)d %(thread)d %(message)s'
            'format': '%(levelname)s %(asctime)s %(module)s %(message)s'
        },
        'simple': {
            'format': '%(levelname)s %(message)s'
        },
    },
    'handlers': {
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': os.path.join(LOGS_DIR, 'debug.log'),
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'noos_services.serializers': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'noos_services.views': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'noos_services.signals': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'noos_services.models': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'noos_services.helper': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'rest_framework.mixins': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'noos_services.tasks': {
            'handlers': ['file'],
            'level': 'DEBUG',
            'propagate': True,
        },
    },
}

ACTIVE_NODES = {}

NOOS_ERROR_CODES = {
    0: ("Model simulation successfully completed (no error)", "FORCING-PROCESSED"),
    1: ("initial position out of model domain", "FORCING-ERROR"),
    2: ("initial position on land", "FORCING-ERROR"),
    3: ("Simulation start and/or end time are not in the forcing availability period \
       [today – 4 days, today + 4 days]", "FORCING-ERROR"),
    4: ("Release time of Lagrangian particle out of the simulation start time and end time windows",
        "FORCING-ERROR"),
    5: ("Drifter type unknown or not available in the model", "FORCING-ERROR"),
    6: ("Model cannot handle the requested set-up -> set-up has been adapted", "FORCING-ERROR"),
    7: ("any other error in the model pre-processing", "FORCING-ERROR"),
    8: ("any error in the model processing", "FORCING-ERROR"),
    9: ("any error in the model post-processing : preparation of the model output", "FORCING-ERROR")
}

# Celery settings
BROKER_URL = os.environ.get("NOOS_BROKER_URL")
if BROKER_URL is None:
    print("No NOOS_BROKER_URL defined and exported in bash environment")
    assert BROKER_URL is not None, "No NOOS_BROKER_URL defined and exported in bash environment"
CELERY_RESULT_BACKEND = 'rpc://'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

# Security settings
# Only with certificate
if DEBUG is False:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_HSTS_SECONDS = 3600
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# At all time
X_FRAME_OPTIONS = 'DENY'
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
